"""Initial database schema migration for Dr. Radar.

This migration creates all 10 entities described in the architecture report:
users, patients, doctors, health_profiles, ecg_records, predictions,
explanations, appointments, consultations, reports.

The existing FastAPI endpoints in ecg-qml/api.py are completely untouched.
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("first_name", sa.String(length=150), nullable=False),
        sa.Column("last_name", sa.String(length=150), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("onboarding_completed", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("profile_completed", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("terms_accepted", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("terms_accepted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("privacy_policy_accepted", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("privacy_policy_accepted_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("research_consent", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("research_consent_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("two_factor_enabled", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("active_sessions_count", sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.Column("last_password_change", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_users_email"),
        sa.CheckConstraint("role IN ('patient', 'doctor')", name="ck_users_role"),
    )
    op.create_index("ix_users_role", "users", ["role"], unique=False)
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    op.create_table(
        "patients",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("dob", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gender", sa.String(length=50), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("language", sa.String(length=50), nullable=True),
        sa.Column("professional_role", sa.String(length=200), nullable=True),
        sa.Column("specialization", sa.String(length=200), nullable=True),
        sa.Column("organization", sa.String(length=300), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.UniqueConstraint("user_id", name="uq_patients_user_id"),
        sa.Index("ix_patients_user_id", "user_id"),
        sa.Index("ix_patients_dob", "dob"),
    )

    op.create_table(
        "doctors",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("specialty", sa.String(length=200), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False, server_default=sa.text("0.0")),
        sa.Column("experience_years", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("available_tag", sa.String(length=100), nullable=True),
        sa.Column("next_available", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_available_today", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("hospital", sa.String(length=300), nullable=True),
        sa.Column("about", sa.Text(), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("slots", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.UniqueConstraint("user_id", name="uq_doctors_user_id"),
        sa.Index("ix_doctors_user_id", "user_id"),
        sa.Index("ix_doctors_specialty", "specialty"),
        sa.Index("ix_doctors_available", "is_available_today"),
    )

    op.create_table(
        "health_profiles",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("primary_goal", sa.String(length=50), nullable=True),
        sa.Column("goal_description", sa.Text(), nullable=True),
        sa.Column("symptoms", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
        sa.Column("conditions", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
        sa.Column("medications", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
        sa.Column("allergies", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
        sa.Column("procedures", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
        sa.Column("family_history", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
        sa.Column("lifestyle", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
        sa.Column("previous_tests", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
        sa.Column("completion_percentage", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.UniqueConstraint("patient_id", name="uq_healthprofiles_patient_id"),
        sa.Index("ix_healthprofiles_patient_id", "patient_id"),
    )

    op.create_table(
        "ecg_records",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("ecg_values", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
        sa.Column("lead", sa.String(length=50), nullable=False, server_default=sa.text("'Lead II'")),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Index("ix_ecgrecords_patient_id", "patient_id"),
        sa.Index("ix_ecgrecords_recorded_at", "recorded_at"),
    )

    op.create_table(
        "predictions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("ecg_record_id", sa.Uuid(), nullable=False),
        sa.Column("predicted_class", sa.Integer(), nullable=False),
        sa.Column("predicted_class_name", sa.String(length=1), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("probabilities", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
        sa.Column("model_mode", sa.String(length=50), nullable=False, server_default=sa.text("'balanced'")),
        sa.Column("pca_features", sa.JSON(), nullable=True),
        sa.Column("quantum_features", sa.JSON(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Index("ix_predictions_ecg_record_id", "ecg_record_id"),
        sa.Index("ix_predictions_predicted_class", "predicted_class"),
        sa.CheckConstraint("predicted_class BETWEEN 0 AND 4", name="ck_predictions_class"),
    )

    op.create_table(
        "explanations",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("prediction_id", sa.Uuid(), nullable=False, unique=True),
        sa.Column("method", sa.String(length=255), nullable=False),
        sa.Column("ranked_features", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
        sa.Column("waveform_importance", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
        sa.Column("xai_metadata", sa.JSON(), nullable=True, server_default=sa.text("'{}'")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Index("ix_explanations_prediction_id", "prediction_id"),
    )

    op.create_table(
        "appointments",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("doctor_id", sa.Uuid(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False, server_default=sa.text("'scheduled'")),
        sa.Column("consultation_type", sa.String(length=50), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Index("ix_appointments_patient_id", "patient_id"),
        sa.Index("ix_appointments_doctor_id", "doctor_id"),
        sa.Index("ix_appointments_status", "status"),
        sa.Index("ix_appointments_start_time", "start_time"),
        sa.UniqueConstraint(
            "patient_id",
            "doctor_id",
            "start_time",
            name="uq_appointments_patient_doctor_start",
            deferrable=True,
            initially="DEFERRED",
        ),
        sa.CheckConstraint(
            "status = ANY(ARRAY['scheduled'::text, 'completed'::text, 'cancelled'::text, 'no_show'::text])",
            name="ck_appointments_status",
        ),
        sa.CheckConstraint(
            "consultation_type = ANY(ARRAY['in_person'::text, 'telehealth'::text, 'follow_up'::text])",
            name="ck_appointments_consultation_type",
        ),
    )

    op.create_table(
        "consultations",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("appointment_id", sa.Uuid(), nullable=False, unique=True),
        sa.Column("doctor_notes", sa.Text(), nullable=True),
        sa.Column("follow_up_required", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("follow_up_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Index("ix_consultations_appointment_id", "appointment_id"),
    )

    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("appointment_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("date", sa.Date, nullable=False),
        sa.Column("bpm_avg", sa.Integer(), nullable=True),
        sa.Column("rhythm_status", sa.String(length=100), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=100), nullable=True),
        sa.Column("is_attention", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("pdf_path", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Index("ix_reports_patient_id", "patient_id"),
        sa.Index("ix_reports_is_attention", "is_attention"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reports")
    op.drop_table("consultations")
    op.drop_table("appointments")
    op.drop_table("explanations")
    op.drop_table("predictions")
    op.drop_table("ecg_records")
    op.drop_table("health_profiles")
    op.drop_table("doctors")
    op.drop_table("patients")
    op.drop_table("users")
    # ### end Alembic commands ###